services:
  - type: web
    name: shopease
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn ecommerce.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopease-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: RENDER
        value: "true"
      - key: DJANGO_SETTINGS_MODULE
        value: "ecommerce.production"
      - key: WEB_CONCURRENCY
        value: "4"

databases:
  - name: shopease-db
    databaseName: shopease
    plan: free 