services:
  - type: web
    name: website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: website-db
          property: connectionString
      - key: STATIC_ROOT
        value: staticfiles
      - key: STATIC_URL
        value: /static/
      - key: DEBUG
        value: false

databases:
  - name: website-db
    plan: free
    databaseName: website
    user: website 